import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my projects',
  projects: [
    {
      id: getId(),
      name: 'CLIMATE CATALYSTS',
      url: 'https://climatecatalysts.netlify.app/',
      repo: 'https://github.com/kushagrakataria/Climate-Catalysts--HOPE-23',
      img: 'https://github.com/kushagrakataria/PortfolioNextjs/blob/main/public/images/ClimateCatalysts.png?raw=true',
      year: 2023,
      tags: ['HTML/CSS', 'Js', 'Bootstrap'],
    },
    {
      id: getId(),
      name: 'FOOD POINT',
      url: 'https://yourfoodpoint.netlify.app/',
      repo: 'https://github.com/kushagrakataria/projects',
      img: 'https://github.com/kushagrakataria/PortfolioNextjs/blob/main/public/images/yourfoodpoint.png?raw=true',
      year: 2022,
      tags: ['React'],
    },
    {
      id: getId(),
      name: 'EDUMILE',
      url: '/404',
      repo: '/404',
      img: 'https://github.com/kushagrakataria/PortfolioNextjs/blob/main/public/images/Edumile%20.png?raw=true',
      year: 2022,
      tags: ['Figma', 'Android Studio'],
    },
    {
      id: getId(),
      name: 'FOURPAWSCO',
      url: 'https://fourpawsco.netlify.app/',
      repo: 'https://github.com/kushagrakataria/fourpaws',
      img: 'https://github.com/kushagrakataria/PortfolioNextjs/blob/main/public/images/fourpawsco.png?raw=true',
      year: 2022,
      tags: ['HTML/CSS', 'Js', 'Bootstrap'],

    },
    {
      id: getId(),
      name: 'PROMO VIDEO CONTEST',
      url: 'https://youtu.be/qXFDHQ99loA',
      repo: '/404',
      img: 'https://github.com/kushagrakataria/PortfolioNextjs/blob/main/public/images/Promo%20Video%20Contest.jpg?raw=true',
      year: 2021,
      tags: ['videoedit',],
    },
    {
      id: getId(),
      name: 'EYE OF DUBAI VIDEOGRAPHY CONTEST',
      url: 'https://youtu.be/XrjgLw_iYzg',
      repo: '/404',
      img: 'https://github.com/kushagrakataria/PortfolioNextjs/blob/main/public/images/REVOLUTION%20OF%20EDUCATION.jpg?raw=true',
      year: 2021,
      tags: ['videoedit'],
    },
    // {
    //   id: getId(),
    //   name: 'todo app',
    //   url: 'https://todo-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/todo-app',
    //   img: 'https://user-images.githubusercontent.com/68834718/152794002-0e7bc583-084b-4c39-83bb-d82d5dd642b2.png',
    //   year: 2022,
    //   tags: ['React', 'Sass', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'weather app',
    //   url: 'https://weather-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/weather-app',
    //   img: 'https://user-images.githubusercontent.com/68834718/148419702-491fa08d-e520-4e2f-b219-374ec7118b2b.png',
    //   year: 2022,
    //   tags: ['Html', 'sass', 'JS', 'jQuery'],
    // },
    // {
    //   id: getId(),
    //   name: 'blogr landing page',
    //   url: 'https://blogr-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/blogr-landing-page',
    //   img: 'https://user-images.githubusercontent.com/68834718/210222542-6455303d-c93e-430b-a5c8-96a431044184.png',
    //   year: 2021,
    //   tags: ['html', 'sass', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'natours',
    //   url: 'https://natours-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/natours',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223114-b4f64b44-2501-49c9-9fb7-b8e53fe654c6.png',
    //   year: 2021,
    //   tags: ['html', 'sass', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'nexter',
    //   url: 'https://vatsalsinghkv.github.io/nexter/',
    //   repo: 'https://github.com/vatsalsinghkv/nexter',
    //   img: 'https://user-images.githubusercontent.com/68834718/210224671-5501c5d9-a8d2-4044-a14c-38fb7e46a113.png',
    //   year: 2021,
    //   tags: ['html', 'sass'],
    // },
    // {
    //   id: getId(),
    //   name: 'IP address tracker',
    //   url: 'https://vatsalsinghkv.github.io/ip-address-tracker/',
    //   repo: 'https://github.com/vatsalsinghkv/ip-address-tracker',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223386-03bcaa20-e649-4b3d-8709-59e42c6d685a.png',
    //   year: 2021,
    //   tags: ['html', 'bootstrap', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'calculator app',
    //   url: 'https://vatsalsinghkv.github.io/calculator-app/',
    //   repo: 'https://github.com/vatsalsinghkv/calculator-app/',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223825-3b68d696-39c6-490c-9433-f315b7efccbd.png',
    //   year: 2021,
    //   tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'pig game',
    //   url: 'https://vatsalsinghkv.github.io/pig-game/',
    //   repo: 'https://github.com/vatsalsinghkv/pig-game',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223527-de7fde7a-244e-4db5-8e33-d561afad6084.png',
    //   year: 2021,
    //   tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'bankist marketing',
    //   url: 'https://vatsalsinghkv.github.io/bankist-marketing/',
    //   repo: 'https://github.com/vatsalsinghkv/bankist-marketing',
    //   img: 'https://user-images.githubusercontent.com/68834718/210225545-989f79c3-cf05-4c53-b48e-b21f373b3734.png',
    //   year: 2021,
    //   tags: ['html', 'CSS', 'JS'],
    // },
  ],
};
